### ISSUE TITLE
Any example of this running with interactive messages?

### ISSUE THREAD

**Issue by davidvexel** [mvaragnat/botkit-express-demo#7]
Hey, thanks for doing this, it's really helpful. I'm just wondering of how to activate the interactive message's payload, I've been trying to replicate the logic from botkit lib but haven't had luck yet. Do you have any example? Thanks in advance.

**Comment by mvaragnat** [comment]
Hey folks,

Just to let you know that 
1) I'm not actively maintaining that repo anymore
2) Since Botkit, Slack API, FB API evolve very quickly, there is a high probability of obsolescence of some parts of the code.

=> If you find a solution to your issue, please consider a PR! I'll happily merge it. This repo is aimed at helping beginners, so let's make it better
